### ISSUE TITLE
CT: Assertion failed: invalid playback rate: NaN

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/keplers-laws#218]
This is occurring in CT for test "listenerOrderRandom", but not on every cycle.

```
keplers-laws : fuzz : unbuilt : listenerOrderRandom
http://128.138.93.172/continuous-testing/ct-snapshots/1701630884724/keplers-laws/keplers-laws_en.html?continuousTest=%7B%22test%22%3A%5B%22keplers-laws%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1701630884724%22%2C%22timestamp%22%3A1701632744869%7D&brand=phet&ea&fuzz&listenerOrder=random
Query: brand=phet&ea&fuzz&listenerOrder=random
Uncaught Error: Assertion failed: invalid playback rate: NaN
Error: Assertion failed: invalid playback rate: NaN
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1701630884724/assert/js/assert.js:28:13)
at assert (SoundClip.ts:276:14)
at setPlaybackRate (OrbitalSound.ts:54:28)
at callback (Multilink.ts:111:10)
at listener (TinyEmitter.ts:123:8)
at emit (ReadOnlyProperty.ts:329:22)
at _notifyListeners (ReadOnlyProperty.ts:276:13)
at unguardedSet (ReadOnlyProperty.ts:260:11)
at set (Property.ts:54:10)
at (EllipticalOrbitEngine.ts:324:36)
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1701630884724%2Fkeplers-laws%2Fkeplers-laws_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22keplers-laws%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1701630884724%22%2C%22timestamp%22%3A1701632744869%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1701630884724%2Fkeplers-laws%2Fkeplers-laws_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22keplers-laws%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1701630884724%22%2C%22timestamp%22%3A1701632744869%7D
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1701630884724/keplers-laws/keplers-laws_en.html?continuousTest=%7B%22test%22%3A%5B%22keplers-laws%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1701630884724%22%2C%22timestamp%22%3A1701632744869%7D&brand=phet&ea&fuzz&listenerOrder=random
[CONSOLE] enabling assert
[CONSOLE] listenerOrder random seed: 785862
[CONSOLE] continuous-test-load
[CONSOLE] Assertion failed: invalid playback rate: NaN
[PAGE ERROR] Error: Error: Assertion failed: invalid playback rate: NaN
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1701630884724/assert/js/assert.js:28:13)
at SoundClip.setPlaybackRate (http://128.138.93.172/continuous-testing/ct-snapshots/1701630884724/chipper/dist/js/tambo/js/sound-generators/SoundClip.js:196:15)
at http://128.138.93.172/continuous-testing/ct-snapshots/1701630884724/chipper/dist/js/keplers-laws/js/common/view/OrbitalSound.js:38:29
at listener (http://128.138.93.172/continuous-testing/ct-snapshots/1701630884724/chipper/dist/js/axon/js/Multilink.js:50:11)
at TinyProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1701630884724/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at NumberProperty._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1701630884724/chipper/dist/js/axon/js/ReadOnlyProperty.js:250:23)
at NumberProperty.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1701630884724/chipper/dist/js/axon/js/ReadOnlyProperty.js:199:14)
at NumberProperty.set (http://128.138.93.172/continuous-testing/ct-snapshots/1701630884724/chipper/dist/js/axon/js/ReadOnlyProperty.js:184:12)
at set value [as value] (http://128.138.93.172/continuous-testing/ct-snapshots/1701630884724/chipper/dist/js/axon/js/Property.js:48:11)
at EllipticalOrbitEngine.update (http://128.138.93.172/continuous-testing/ct-snapshots/1701630884724/chipper/dist/js/keplers-laws/js/common/model/EllipticalOrbitEngine.js:278:38)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: reentry detected, value=Vector2(-0.9199999999999999, -0.10000000000000142), oldValue=Vector2(2, 0)
[PAGE ERROR] Error: Error: Assertion failed: reentry detected, value=Vector2(-0.9199999999999999, -0.10000000000000142), oldValue=Vector2(2, 0)
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1701630884724/assert/js/assert.js:28:13)
at Vector2Property._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1701630884724/chipper/dist/js/axon/js/ReadOnlyProperty.js:248:15)
at Vector2Property.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1701630884724/chipper/dist/js/axon/js/ReadOnlyProperty.js:199:14)
at Vector2Property.set (http://128.138.93.172/continuous-testing/ct-snapshots/1701630884724/chipper/dist/js/axon/js/ReadOnlyProperty.js:184:12)
at set value [as value] (http://128.138.93.172/continuous-testing/ct-snapshots/1701630884724/chipper/dist/js/axon/js/Property.js:48:11)
at DragListener.reposition (http://128.138.93.172/continuous-testing/ct-snapshots/1701630884724/chipper/dist/js/scenery/js/listeners/DragListener.js:529:36)
at http://128.138.93.172/continuous-testing/ct-snapshots/1701630884724/chipper/dist/js/scenery/js/listeners/DragListener.js:216:12
at DragListener.onPress (http://128.138.93.172/continuous-testing/ct-snapshots/1701630884724/chipper/dist/js/scenery/js/listeners/PressListener.js:528:17)
at PhetioAction.execute (http://128.138.93.172/continuous-testing/ct-snapshots/1701630884724/chipper/dist/js/tandem/js/PhetioAction.js:133:17)
at DragListener.press (http://128.138.93.172/continuous-testing/ct-snapshots/1701630884724/chipper/dist/js/scenery/js/listeners/PressListener.js:302:23)
[CONSOLE] continuous-test-error
[CONSOLE] Assertion failed: reentry detected, value=Vector2(0.18790447353391512, -1.803882945925585), oldValue=Vector2(-0.9199999999999999, -0.10000000000000142)
[PAGE ERROR] Error: Error: Assertion failed: reentry detected, value=Vector2(0.18790447353391512, -1.803882945925585), oldValue=Vector2(-0.9199999999999999, -0.10000000000000142)
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1701630884724/assert/js/assert.js:28:13)
at Vector2Property._notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1701630884724/chipper/dist/js/axon/js/ReadOnlyProperty.js:248:15)
at Vector2Property.unguardedSet (http://128.138.93.172/continuous-testing/ct-snapshots/1701630884724/chipper/dist/js/axon/js/ReadOnlyProperty.js:199:14)
at Vector2Property.set (http://128.138.93.172/continuous-testing/ct-snapshots/1701630884724/chipper/dist/js/axon/js/ReadOnlyProperty.js:184:12)
at set value [as value] (http://128.138.93.172/continuous-testing/ct-snapshots/1701630884724/chipper/dist/js/axon/js/Property.js:48:11)
at DragListener.reposition (http://128.138.93.172/continuous-testing/ct-snapshots/1701630884724/chipper/dist/js/scenery/js/listeners/DragListener.js:529:36)
at DragListener._dragAction.PhetioAction.parameters.name (http://128.138.93.172/continuous-testing/ct-snapshots/1701630884724/chipper/dist/js/scenery/js/listeners/DragListener.js:163:16)
at PhetioAction.execute (http://128.138.93.172/continuous-testing/ct-snapshots/1701630884724/chipper/dist/js/tandem/js/PhetioAction.js:133:17)
at DragListener.drag (http://128.138.93.172/continuous-testing/ct-snapshots/1701630884724/chipper/dist/js/scenery/js/listeners/DragListener.js:299:22)
at DragListener.pointerMove (http://128.138.93.172/continuous-testing/ct-snapshots/1701630884724/chipper/dist/js/scenery/js/listeners/PressListener.js:681:14)
[CONSOLE] continuous-test-error

id: "Sparky Node Puppeteer"
Snapshot from 12/3/2023, 12:14:44 PM
```

**Comment by AgustinVallejo** [comment]
The solution didn't work. CT is still ocasionally reporting issues. Will look further into it.

**Comment by pixelzoom** [comment]
Here's the other variation that occurs in CT, down in EllipticalOrbitEngine `calculateOrbitalDivisions`:

```
keplers-laws : fuzz : unbuilt : listenerOrderRandom
http://128.138.93.172/continuous-testing/ct-snapshots/1702689857271/keplers-laws/keplers-laws_en.html?continuousTest=%7B%22test%22%3A%5B%22keplers-laws%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1702689857271%22%2C%22timestamp%22%3A1702692305796%7D&brand=phet&ea&fuzz&listenerOrder=random
Query: brand=phet&ea&fuzz&listenerOrder=random
Uncaught Error: Assertion failed: validation failed:
Property value not valid: Failed validation for validators[0]: Should not be NaN: value failed isValidValue: NaN
prunedValidator:
{
"valueType": "number",
"phetioType": {
"validator": {
"valueType": "number",
"validationMessage": "Validation failed IOType Validator: NumberIO"
},
"typeName": "NumberIO"
},
"validators": [
{
"validationMessage": "Should not be NaN"
},
{}
]
}
Error: Assertion failed: validation failed:
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1702689857271/assert/js/assert.js:28:13)
at assert (validate.ts:32:16)
at validate (ReadOnlyProperty.ts:310:14)
at _notifyListeners (ReadOnlyProperty.ts:276:13)
at unguardedSet (ReadOnlyProperty.ts:260:11)
at set (Property.ts:54:10)
at (EllipticalOrbitEngine.ts:488:45)
at Array.forEach
at forEach (EllipticalOrbitEngine.ts:455:22)
at calculateOrbitalDivisions (EllipticalOrbitEngine.ts:648:9)
[URL] http://128.138.93.172/continuous-testing/aqua/html/sim-test.html?url=..%2F..%2Fct-snapshots%2F1702689857271%2Fkeplers-laws%2Fkeplers-laws_en.html&simQueryParameters=brand%3Dphet%26ea%26fuzz%26listenerOrder%3Drandom&testInfo=%7B%22test%22%3A%5B%22keplers-laws%22%2C%22fuzz%22%2C%22unbuilt%22%2C%22listenerOrderRandom%22%5D%2C%22snapshotName%22%3A%22snapshot-1702689857271%22%2C%22timestamp%22%3A1702692305796%7D
...
```

**Comment by AgustinVallejo** [comment]
Managed to identify a problem: Sometimes the escape speed was not being properly re calculated on reset (and possibly other situations). So the actual escape speed should have been small but it stayed big, making the enforceEscapeSpeed function "lazy" and thus the orbital equations didn't work.

With the above change, escape speed is calculated always before the rest of the orbital calculations. Let's hope this fixes the red in CT.

**Comment by AgustinVallejo** [comment]
CT looking green! Closing this issue

**Comment by phet-dev** [comment]
Reopening because there is a TODO marked for this issue.
