### ISSUE TITLE
CT Error: Did not get next-test message in 400000ms

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/keplers-laws#247]
```
keplers-laws : phet-io-wrappers-tests : assert
Tried to run 3 times, never completed, failure: Error: Error: Did not get next-test message in 400000ms (currentSendingCount 0): ["keplers-laws","phet-io-wrappers-tests","assert"]
[URL] http://128.138.93.172/continuous-testing/aqua/html/qunit-test.html?url=..%2F..%2Fct-snapshots%2F1706147536981%2Fphet-io-wrappers%2Fphet-io-wrappers-tests.html%3Fsim%3Dkeplers-laws%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue&duration=600000&testInfo=%7B%22test%22%3A%5B%22keplers-laws%22%2C%22phet-io-wrappers-tests%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1706147536981%22%2C%22timestamp%22%3A1706148674001%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/qunit-test.html?url=..%2F..%2Fct-snapshots%2F1706147536981%2Fphet-io-wrappers%2Fphet-io-wrappers-tests.html%3Fsim%3Dkeplers-laws%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue&duration=600000&testInfo=%7B%22test%22%3A%5B%22keplers-laws%22%2C%22phet-io-wrappers-tests%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1706147536981%22%2C%22timestamp%22%3A1706148674001%7D
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/phet-io-wrappers/phet-io-wrappers-tests.html?sim=keplers-laws&phetioDebug=true&phetioWrapperDebug=true
[CONSOLE] Failed to load resource: the server responded with a status of 404 (Not Found): http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/phet-io-wrappers/phet-io-wrappers-strings_en.json
[CONSOLE] enabling assert
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/keplers-laws/keplers-laws_en.html?brand=phet-io&postMessageOnError&sim=keplers-laws&phetioDebug=true&phetioWrapperDebug=true&ea
[CONSOLE] enabling assert
[DETACHED] http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/keplers-laws/keplers-laws_en.html?brand=phet-io&postMessageOnError&sim=keplers-laws&phetioDebug=true&phetioWrapperDebug=true&ea
[ATTACHED]
[NAVIGATED] about:blank
[CONSOLE] Deprecation warning: launchSim is deprecated, use launchSimulation instead.
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/keplers-laws/keplers-laws_en.html?brand=phet-io&postMessageOnError&sim=keplers-laws&phetioDebug=true&phetioWrapperDebug=true&ea
[CONSOLE] enabling assert
[CONSOLE] Deprecation warning: getStateForObject is deprecated, use getPhetioElementState instead.
[DETACHED] http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/keplers-laws/keplers-laws_en.html?brand=phet-io&postMessageOnError&sim=keplers-laws&phetioDebug=true&phetioWrapperDebug=true&ea
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/keplers-laws/keplers-laws_en.html?brand=phet-io&ea&postMessageOnError&sim=keplers-laws&phetioDebug=true&phetioWrapperDebug=true&fuzz
[CONSOLE] enabling assert
[DETACHED] http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/keplers-laws/keplers-laws_en.html?brand=phet-io&ea&postMessageOnError&sim=keplers-laws&phetioDebug=true&phetioWrapperDebug=true&fuzz
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/keplers-laws/keplers-laws_en.html?brand=phet-io&ea&postMessageOnError
[CONSOLE] enabling assert
[DETACHED] http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/keplers-laws/keplers-laws_en.html?brand=phet-io&ea&postMessageOnError
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/keplers-laws/keplers-laws_en.html?brand=phet-io&ea&postMessageOnError
[CONSOLE] enabling assert
[DETACHED] http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/keplers-laws/keplers-laws_en.html?brand=phet-io&ea&postMessageOnError
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/keplers-laws/keplers-laws_en.html?brand=phet-io&ea&postMessageOnError
[CONSOLE] enabling assert
[CONSOLE] Assertion failed: args should be an array
[CONSOLE] Assertion failed: callback should be a function
[CONSOLE] Error from phetioClient JSHandle@error
[DETACHED] http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/keplers-laws/keplers-laws_en.html?brand=phet-io&ea&postMessageOnError
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/keplers-laws/keplers-laws_en.html?brand=phet-io&ea&postMessageOnError
[CONSOLE] enabling assert
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/phet-io-wrappers/phet-io-wrappers-tests.html?sim=keplers-laws&phetioDebug=true&phetioWrapperDebug=true&phetioClientName=NewSpecialClientName
[CONSOLE] enabling assert
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/phet-io-wrappers/phet-io-wrappers-tests.html?sim=keplers-laws&phetioDebug=true&phetioWrapperDebug=true
[DETACHED] http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/keplers-laws/keplers-laws_en.html?brand=phet-io&ea&postMessageOnError
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/keplers-laws/keplers-laws_en.html?brand=phet-io&ea&postMessageOnError&locales=*
[CONSOLE] enabling assert
[CONSOLE] Assertion failed: accessed value outside of dependency tracking
[CONSOLE] Assertion failed: mismatched index, possible start/end mismatch. Likely this is downstream of another error, try pausing on caught exceptions.
[PAGE ERROR] Error: Error: Assertion failed: mismatched index, possible start/end mismatch. Likely this is downstream of another error, try pausing on caught exceptions.
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/assert/js/assert.js:28:13)
at DataStream.end (http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/chipper/dist/js/phet-io/js/dataStream.js:253:15)
at PhetioCommandProcessor.phetioEndEvent (http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/chipper/dist/js/tandem/js/PhetioObject.js:437:30)
at http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/chipper/dist/js/phet-io/js/phetioCommandProcessor.js:135:18
[PAGE ERROR] Error: Error: Assertion failed: accessed value outside of dependency tracking
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/assert/js/assert.js:28:13)
at Vector2Property.get (http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/chipper/dist/js/axon/js/ReadOnlyProperty.js:167:19)
at get value (http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/chipper/dist/js/axon/js/ReadOnlyProperty.js:305:17)
at get value [as value] (http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/chipper/dist/js/axon/js/Property.js:39:18)
at FlowConstraint.layout (http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/chipper/dist/js/scenery/js/layout/constraints/FlowConstraint.js:175:53)
at FlowConstraint.updateLayout (http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/chipper/dist/js/scenery/js/layout/constraints/LayoutConstraint.js:188:14)
at FlowConstraint.updateLayoutAutomatically (http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/chipper/dist/js/scenery/js/layout/constraints/LayoutConstraint.js:201:12)
at TinyStaticProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at TinyStaticProperty.notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/chipper/dist/js/axon/js/TinyStaticProperty.js:49:10)
at Text.validateBounds (http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/chipper/dist/js/scenery/js/nodes/Node.js:1333:31)
[PAGE ERROR] Error: Error: Assertion failed: mismatched index, possible start/end mismatch. Likely this is downstream of another error, try pausing on caught exceptions.
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/assert/js/assert.js:28:13)
at DataStream.end (http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/chipper/dist/js/phet-io/js/dataStream.js:253:15)
at PhetioCommandProcessor.phetioEndEvent (http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/chipper/dist/js/tandem/js/PhetioObject.js:437:30)
at http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/chipper/dist/js/phet-io/js/phetioCommandProcessor.js:135:18
Error: Did not get next-test message in 400000ms (currentSendingCount 0): ["keplers-laws","phet-io-wrappers-tests","assert"]

id: "Sparky Node Puppeteer"
Snapshot from 1/24/2024, 6:52:16 PM

----------------------------------

keplers-laws : phet-io-wrappers-tests : assert
Tried to run 3 times, never completed, failure: Error: Error: Did not get next-test message in 400000ms (currentSendingCount 0): ["keplers-laws","phet-io-wrappers-tests","assert"]
[URL] http://128.138.93.172/continuous-testing/aqua/html/qunit-test.html?url=..%2F..%2Fct-snapshots%2F1706147536981%2Fphet-io-wrappers%2Fphet-io-wrappers-tests.html%3Fsim%3Dkeplers-laws%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue&duration=600000&testInfo=%7B%22test%22%3A%5B%22keplers-laws%22%2C%22phet-io-wrappers-tests%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1706147536981%22%2C%22timestamp%22%3A1706149819882%7D
[NAVIGATED] http://128.138.93.172/continuous-testing/aqua/html/qunit-test.html?url=..%2F..%2Fct-snapshots%2F1706147536981%2Fphet-io-wrappers%2Fphet-io-wrappers-tests.html%3Fsim%3Dkeplers-laws%26phetioDebug%3Dtrue%26phetioWrapperDebug%3Dtrue&duration=600000&testInfo=%7B%22test%22%3A%5B%22keplers-laws%22%2C%22phet-io-wrappers-tests%22%2C%22assert%22%5D%2C%22snapshotName%22%3A%22snapshot-1706147536981%22%2C%22timestamp%22%3A1706149819882%7D
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/phet-io-wrappers/phet-io-wrappers-tests.html?sim=keplers-laws&phetioDebug=true&phetioWrapperDebug=true
[CONSOLE] Failed to load resource: the server responded with a status of 404 (Not Found): http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/phet-io-wrappers/phet-io-wrappers-strings_en.json
[CONSOLE] enabling assert
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/keplers-laws/keplers-laws_en.html?brand=phet-io&postMessageOnError&sim=keplers-laws&phetioDebug=true&phetioWrapperDebug=true&ea
[CONSOLE] enabling assert
[DETACHED] http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/keplers-laws/keplers-laws_en.html?brand=phet-io&postMessageOnError&sim=keplers-laws&phetioDebug=true&phetioWrapperDebug=true&ea
[ATTACHED]
[NAVIGATED] about:blank
[CONSOLE] Deprecation warning: launchSim is deprecated, use launchSimulation instead.
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/keplers-laws/keplers-laws_en.html?brand=phet-io&postMessageOnError&sim=keplers-laws&phetioDebug=true&phetioWrapperDebug=true&ea
[CONSOLE] enabling assert
[CONSOLE] Deprecation warning: getStateForObject is deprecated, use getPhetioElementState instead.
[DETACHED] http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/keplers-laws/keplers-laws_en.html?brand=phet-io&postMessageOnError&sim=keplers-laws&phetioDebug=true&phetioWrapperDebug=true&ea
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/keplers-laws/keplers-laws_en.html?brand=phet-io&ea&postMessageOnError&sim=keplers-laws&phetioDebug=true&phetioWrapperDebug=true&fuzz
[CONSOLE] enabling assert
[DETACHED] http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/keplers-laws/keplers-laws_en.html?brand=phet-io&ea&postMessageOnError&sim=keplers-laws&phetioDebug=true&phetioWrapperDebug=true&fuzz
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/keplers-laws/keplers-laws_en.html?brand=phet-io&ea&postMessageOnError
[CONSOLE] enabling assert
[DETACHED] http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/keplers-laws/keplers-laws_en.html?brand=phet-io&ea&postMessageOnError
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/keplers-laws/keplers-laws_en.html?brand=phet-io&ea&postMessageOnError
[CONSOLE] enabling assert
[DETACHED] http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/keplers-laws/keplers-laws_en.html?brand=phet-io&ea&postMessageOnError
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/keplers-laws/keplers-laws_en.html?brand=phet-io&ea&postMessageOnError
[CONSOLE] enabling assert
[CONSOLE] Assertion failed: args should be an array
[CONSOLE] Assertion failed: callback should be a function
[CONSOLE] Error from phetioClient JSHandle@error
[DETACHED] http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/keplers-laws/keplers-laws_en.html?brand=phet-io&ea&postMessageOnError
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/keplers-laws/keplers-laws_en.html?brand=phet-io&ea&postMessageOnError
[CONSOLE] enabling assert
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/phet-io-wrappers/phet-io-wrappers-tests.html?sim=keplers-laws&phetioDebug=true&phetioWrapperDebug=true&phetioClientName=NewSpecialClientName
[CONSOLE] enabling assert
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/phet-io-wrappers/phet-io-wrappers-tests.html?sim=keplers-laws&phetioDebug=true&phetioWrapperDebug=true
[DETACHED] http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/keplers-laws/keplers-laws_en.html?brand=phet-io&ea&postMessageOnError
[ATTACHED]
[NAVIGATED] about:blank
[NAVIGATED] http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/keplers-laws/keplers-laws_en.html?brand=phet-io&ea&postMessageOnError&locales=*
[CONSOLE] enabling assert
[CONSOLE] Assertion failed: accessed value outside of dependency tracking
[CONSOLE] Assertion failed: mismatched index, possible start/end mismatch. Likely this is downstream of another error, try pausing on caught exceptions.
[PAGE ERROR] Error: Error: Assertion failed: mismatched index, possible start/end mismatch. Likely this is downstream of another error, try pausing on caught exceptions.
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/assert/js/assert.js:28:13)
at DataStream.end (http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/chipper/dist/js/phet-io/js/dataStream.js:253:15)
at PhetioCommandProcessor.phetioEndEvent (http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/chipper/dist/js/tandem/js/PhetioObject.js:437:30)
at http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/chipper/dist/js/phet-io/js/phetioCommandProcessor.js:135:18
[PAGE ERROR] Error: Error: Assertion failed: accessed value outside of dependency tracking
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/assert/js/assert.js:28:13)
at Vector2Property.get (http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/chipper/dist/js/axon/js/ReadOnlyProperty.js:167:19)
at get value (http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/chipper/dist/js/axon/js/ReadOnlyProperty.js:305:17)
at get value [as value] (http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/chipper/dist/js/axon/js/Property.js:39:18)
at FlowConstraint.layout (http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/chipper/dist/js/scenery/js/layout/constraints/FlowConstraint.js:175:53)
at FlowConstraint.updateLayout (http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/chipper/dist/js/scenery/js/layout/constraints/LayoutConstraint.js:188:14)
at FlowConstraint.updateLayoutAutomatically (http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/chipper/dist/js/scenery/js/layout/constraints/LayoutConstraint.js:201:12)
at TinyStaticProperty.emit (http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/chipper/dist/js/axon/js/TinyEmitter.js:96:9)
at TinyStaticProperty.notifyListeners (http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/chipper/dist/js/axon/js/TinyStaticProperty.js:49:10)
at Text.validateBounds (http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/chipper/dist/js/scenery/js/nodes/Node.js:1333:31)
[PAGE ERROR] Error: Error: Assertion failed: mismatched index, possible start/end mismatch. Likely this is downstream of another error, try pausing on caught exceptions.
at window.assertions.assertFunction (http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/assert/js/assert.js:28:13)
at DataStream.end (http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/chipper/dist/js/phet-io/js/dataStream.js:253:15)
at PhetioCommandProcessor.phetioEndEvent (http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/chipper/dist/js/tandem/js/PhetioObject.js:437:30)
at http://128.138.93.172/continuous-testing/ct-snapshots/1706147536981/chipper/dist/js/phet-io/js/phetioCommandProcessor.js:135:18
Error: Did not get next-test message in 400000ms (currentSendingCount 0): ["keplers-laws","phet-io-wrappers-tests","assert"]

id: "Sparky Node Puppeteer"
Snapshot from 1/24/2024, 6:52:16 PM
```

**Comment by samreid** [comment]
This is likely related to the DerivedProperty identified in https://github.com/phetsims/faradays-electromagnetic-lab/issues/65#issuecomment-1915194464. Feel free to commit the patch or use it to investigate which non-dependency is being queried.

**Comment by samreid** [comment]
@AgustinVallejo asked me to commit this workaround.

**Comment by samreid** [comment]
I opted out of the strictness check, closing.
